// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDMTRE8poj6Yw8hYQzdiuMQxA9dZVyeqJA',
    appId: '1:21355046994:web:ebd04b9e2febb7c921178b',
    messagingSenderId: '21355046994',
    projectId: 'fec-site-api',
    authDomain: 'fec-site-api.firebaseapp.com',
    storageBucket: 'fec-site-api.appspot.com',
    measurementId: 'G-4F0Y2EL6RB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCVpdULqIZYh8a8A2wtzT4evoTRAWoV-DM',
    appId: '1:21355046994:android:e8af3364f903f02f21178b',
    messagingSenderId: '21355046994',
    projectId: 'fec-site-api',
    storageBucket: 'fec-site-api.appspot.com',
  );
}
